trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'simplq/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'latest'

- task: Docker@2
  displayName: Build docker image
  inputs:
    repository: $(DOCKER_REPOSITORY)
    command: build
    Dockerfile: simplq/Dockerfile
    buildContext: simplq/
    tags: |
      latest

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'AWS Service Connection (personal)'
    regionName: 'ap-southeast-1'
    imageSource: 'imagename'
    repositoryName: 'backend'
    forceDockerNamingConventions: true
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
