trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'


steps:
# - task: JavaToolInstaller@0
#   inputs:
#     versionSpec: '11'
#     jdkArchitectureOption: 'x64'
#     jdkSourceOption: 'PreInstalled'
- task: Maven@3
  inputs:
    mavenPomFile: 'simplq/pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: Docker@2
  displayName: Build docker image
  inputs:
    repository: '475033807538.dkr.ecr.ap-southeast-1.amazonaws.com/backend'
    command: 'build'
    Dockerfile: 'simplq/Dockerfile'
    buildContext: 'simplq/'
    tags: 'latest'

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'AWS Service Connection (personal)'
    regionName: 'ap-southeast-1'
    imageSource: 'imagename'
    repositoryName: 'backend'
    forceDockerNamingConventions: true
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
